
project_id = "rdthioybiyrnhfynxxpx"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[analytics]
enabled = false

[experimental]
postgres_search_path = ["public", "extensions"]
multisite = false
postgres_storage = false
postgres_functions = false

[functions.get-deals]
verify_jwt = false

[functions.get-flipkart-offers]
verify_jwt = false
