
services:
  - type: web
    name: discount-hub
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist
    envVars:
      - key: NODE_ENV
        value: production
